version: "3.8" 
services:
  wardrobe-be:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: wardrobe-be
    ports:
      - "3001:3001"
    env_file:
      - ./back-end/.env
    environment:
      - NODE_ENV=production
    networks:
      - dokploy-network
    restart: unless-stopped

  wardrobe-fe:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://72.62.247.116:3001
    container_name: wardrobe-fe
    ports:
      - "8080:80"
    depends_on:
      - wardrobe-be
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
