services:
  wardrobe-be:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: wardrobe-be
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CHROMADB_URL=${CHROMADB_URL}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
