version: "3.8" 
services:
  wardrobe-be:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: wardrobe-be
    ports:
      - "${{environment.API_PORT}}:${{environment.API_PORT}}"
    # Loại bỏ env_file nếu bạn đã truyền biến từ Dokploy
    environment:
      - NODE_ENV=production
      - MONGO_URI=${{environment.MONGO_URI}}
      - JWT_SECRET=${{environment.JWT_SECRET}}
      - JWT_EXPIRE=${{environment.JWT_EXPIRE}}
      - CLOUDINARY_CLOUD_NAME=${{environment.CLOUDINARY_CLOUD_NAME}}
      - CLOUDINARY_API_KEY=${{environment.CLOUDINARY_API_KEY}}
      - CLOUDINARY_API_SECRET=${{environment.CLOUDINARY_API_SECRET}}
    networks:
      - dokploy-network
    restart: unless-stopped

  wardrobe-fe:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${{environment.HOST}}:${{environment.API_PORT}}
    container_name: wardrobe-fe
    ports:
      - "${{environment.UI_PORT}}:80" # Lưu ý phần port đích (80)
    depends_on:
      - wardrobe-be
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
