/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type {
  MarkReadDto,
  NotificationDto
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getNotifications = () => {
/**
 * @summary Get current user notifications
 */
const notificationsControllerGetNotifications = (

 options?: SecondParameter<typeof customInstance<NotificationDto[]>>,) => {
      return customInstance<NotificationDto[]>(
      {url: `/notifications`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Mark notification as read
 */
const notificationsControllerMarkAsRead = (
    id: string,
    markReadDto: MarkReadDto,
 options?: SecondParameter<typeof customInstance<NotificationDto>>,) => {
      return customInstance<NotificationDto>(
      {url: `/notifications/${id}/read`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: markReadDto
    },
      options);
    }
  return {notificationsControllerGetNotifications,notificationsControllerMarkAsRead}};
export type NotificationsControllerGetNotificationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotifications>['notificationsControllerGetNotifications']>>>
export type NotificationsControllerMarkAsReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNotifications>['notificationsControllerMarkAsRead']>>>
