/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type {
  ChangePasswordDto,
  UpdateProfileDto
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getProfile = () => {
/**
 * @summary Get current user profile
 */
const usersControllerGetProfile = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/profile`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Update profile info (name, phone, bio, measurements, styles)
 */
const usersControllerUpdateProfile = (
    updateProfileDto: UpdateProfileDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileDto
    },
      options);
    }
  /**
 * @summary Upload / change profile avatar
 */
const usersControllerUploadAvatar = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/profile/avatar`, method: 'POST'
    },
      options);
    }
  /**
 * @summary Change password (requires old password)
 */
const usersControllerChangePassword = (
    changePasswordDto: ChangePasswordDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/profile/change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordDto
    },
      options);
    }
  return {usersControllerGetProfile,usersControllerUpdateProfile,usersControllerUploadAvatar,usersControllerChangePassword}};
export type UsersControllerGetProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfile>['usersControllerGetProfile']>>>
export type UsersControllerUpdateProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfile>['usersControllerUpdateProfile']>>>
export type UsersControllerUploadAvatarResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfile>['usersControllerUploadAvatar']>>>
export type UsersControllerChangePasswordResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getProfile>['usersControllerChangePassword']>>>
