/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type {
  CreateOutfitDto,
  UpdateOutfitDto
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getOutfits = () => {
const outfitsControllerCreate = (
    createOutfitDto: CreateOutfitDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/outfits`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOutfitDto
    },
      options);
    }
  const outfitsControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/outfits`, method: 'GET'
    },
      options);
    }
  const outfitsControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/outfits/${id}`, method: 'GET'
    },
      options);
    }
  const outfitsControllerUpdate = (
    id: string,
    updateOutfitDto: UpdateOutfitDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/outfits/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateOutfitDto
    },
      options);
    }
  const outfitsControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/outfits/${id}`, method: 'DELETE'
    },
      options);
    }
  return {outfitsControllerCreate,outfitsControllerFindAll,outfitsControllerFindOne,outfitsControllerUpdate,outfitsControllerRemove}};
export type OutfitsControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOutfits>['outfitsControllerCreate']>>>
export type OutfitsControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOutfits>['outfitsControllerFindAll']>>>
export type OutfitsControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOutfits>['outfitsControllerFindOne']>>>
export type OutfitsControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOutfits>['outfitsControllerUpdate']>>>
export type OutfitsControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOutfits>['outfitsControllerRemove']>>>
