/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const webhooksControllerHandleCloudinaryWebhook = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/webhooks/cloudinary`, method: 'POST', signal
    },
      options);
    }



export const getWebhooksControllerHandleCloudinaryWebhookMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerHandleCloudinaryWebhook>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerHandleCloudinaryWebhook>>, TError,void, TContext> => {

const mutationKey = ['webhooksControllerHandleCloudinaryWebhook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhooksControllerHandleCloudinaryWebhook>>, void> = () => {


          return  webhooksControllerHandleCloudinaryWebhook(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhooksControllerHandleCloudinaryWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof webhooksControllerHandleCloudinaryWebhook>>>

    export type WebhooksControllerHandleCloudinaryWebhookMutationError = unknown

    export const useWebhooksControllerHandleCloudinaryWebhook = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerHandleCloudinaryWebhook>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhooksControllerHandleCloudinaryWebhook>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWebhooksControllerHandleCloudinaryWebhookMutationOptions(options), queryClient);
    }
