/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type {
  CreateFavoriteDto
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getFavorites = () => {
const favoritesControllerCreate = (
    createFavoriteDto: CreateFavoriteDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/favorites`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFavoriteDto
    },
      options);
    }
  const favoritesControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/favorites`, method: 'GET'
    },
      options);
    }
  const favoritesControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/favorites/${id}`, method: 'GET'
    },
      options);
    }
  const favoritesControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/favorites/${id}`, method: 'DELETE'
    },
      options);
    }
  const favoritesControllerRemoveByItemId = (
    itemId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/favorites/item/${itemId}`, method: 'DELETE'
    },
      options);
    }
  return {favoritesControllerCreate,favoritesControllerFindAll,favoritesControllerFindOne,favoritesControllerRemove,favoritesControllerRemoveByItemId}};
export type FavoritesControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFavorites>['favoritesControllerCreate']>>>
export type FavoritesControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFavorites>['favoritesControllerFindAll']>>>
export type FavoritesControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFavorites>['favoritesControllerFindOne']>>>
export type FavoritesControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFavorites>['favoritesControllerRemove']>>>
export type FavoritesControllerRemoveByItemIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFavorites>['favoritesControllerRemoveByItemId']>>>
