/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type { CreateOutfitDtoSeason } from './createOutfitDtoSeason';

export interface CreateOutfitDto {
  name: string;
  description?: string;
  /** Array of Item ObjectIds */
  items: string[];
  tags?: string[];
  season?: CreateOutfitDtoSeason;
}
