/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type { CreateLocationDtoType } from './createLocationDtoType';

export interface CreateLocationDto {
  name: string;
  type: CreateLocationDtoType;
  /** Parent Location ID */
  parent?: string;
}
