/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export type CreateOutfitDtoSeason = typeof CreateOutfitDtoSeason[keyof typeof CreateOutfitDtoSeason];


export const CreateOutfitDtoSeason = {
  Spring: 'Spring',
  Summer: 'Summer',
  Autumn: 'Autumn',
  Winter: 'Winter',
  All: 'All',
} as const;
