/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type { CreateOutfitDtoSeason } from './createOutfitDtoSeason';
import type { OutfitItemDto } from './outfitItemDto';

export interface CreateOutfitDto {
  name: string;
  description?: string;
  /** Array of Items with spatial properties */
  items: OutfitItemDto[];
  tags?: string[];
  season?: CreateOutfitDtoSeason;
}
