/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export type DashboardControllerGetHomeDashboardParams = {
/**
 * Latitude of the user's location (defaults to Ho Chi Minh City)
 */
lat?: number;
/**
 * Longitude of the user's location (defaults to Ho Chi Minh City)
 */
lon?: number;
};
