/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type { OotdResponseDto } from './ootdResponseDto';
import type { RecentItemDto } from './recentItemDto';
import type { WardrobeStatsDto } from './wardrobeStatsDto';
import type { WeatherResponseDto } from './weatherResponseDto';

export interface DashboardResponseDto {
  /** Current weather at the user's location */
  weather: WeatherResponseDto;
  /** AI-powered Outfit Of The Day recommendation */
  ootd: OotdResponseDto;
  /** Last 5 items added to the wardrobe */
  recentItems: RecentItemDto[];
  /** Aggregate statistics of the wardrobe */
  stats: WardrobeStatsDto;
}
