/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export * from './createFavoriteDto';
export * from './createLocationDto';
export * from './createLocationDtoType';
export * from './itemsControllerCreateBody';
export * from './itemsControllerUpdateBody';
export * from './loginDto';
export * from './registerDto';
export * from './updateLocationDto';
export * from './updateLocationDtoType';
