/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export type ItemsControllerUpdateAttributeBody = {
  name?: string;
};
