/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export type ItemsControllerUpdateBody = {
  name?: string;
  description?: string;
  price?: number;
  location?: string;
  brand?: string;
  category?: string;
  color?: string;
  size?: string;
  style?: string;
  seasonCode?: string;
  neckline?: string;
  occasion?: string;
  sleeveLength?: string;
  shoulder?: string;
  file?: Blob;
};
