/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type { OotdItemDto } from './ootdItemDto';
import type { OotdResponseDtoSource } from './ootdResponseDtoSource';

export interface OotdResponseDto {
  /** Array of recommended items forming the Outfit Of The Day */
  items: OotdItemDto[];
  /** Source of the recommendation: "ai" = Gemini responded, "fallback" = rule-based logic was used */
  source: OotdResponseDtoSource;
  /** Human-readable explanation of why this outfit was chosen */
  reason?: string;
}
