/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

/**
 * Source of the recommendation: "ai" = Gemini responded, "fallback" = rule-based logic was used
 */
export type OotdResponseDtoSource = typeof OotdResponseDtoSource[keyof typeof OotdResponseDtoSource];


export const OotdResponseDtoSource = {
  ai: 'ai',
  fallback: 'fallback',
} as const;
