/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export interface RecentItemDto {
  _id: string;
  name: string;
  category: string;
  color: string;
  images: string[];
  createdAt: string;
}
