/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
}
