/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateBodyMeasurementsDto } from './updateBodyMeasurementsDto';
import type { UpdateStylePreferencesDto } from './updateStylePreferencesDto';

export interface UpdateProfileDto {
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  bio?: string;
  measurements?: UpdateBodyMeasurementsDto;
  stylePreferences?: UpdateStylePreferencesDto;
}
