/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateLocationDtoType } from './updateLocationDtoType';

export interface UpdateLocationDto {
  name?: string;
  type?: UpdateLocationDtoType;
  parent?: string;
}
