/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateBodyMeasurementsDto {
  /** Height in cm */
  height?: number;
  /** Weight in kg */
  weight?: number;
  chest?: number;
  waist?: number;
  hips?: number;
}
