/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export interface WardrobeStatsDto {
  /** Total number of items in the wardrobe */
  totalItems: number;
  /** Total estimated value of all items (sum of prices) */
  totalValue: number;
}
