/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */

export interface WeatherResponseDto {
  /** Current temperature in Celsius */
  temperature: number;
  /** Feels-like temperature in Celsius */
  feelsLike: number;
  /** Humidity percentage */
  humidity: number;
  /** OpenWeatherMap icon code */
  iconCode: string;
  /** Full URL for the weather icon */
  iconUrl: string;
  /** General weather condition (e.g. Rain, Clear, Clouds) */
  condition: string;
  /** Short human-readable weather description */
  description: string;
  /** City name resolved from coordinates */
  cityName: string;
}
