version: '3.8'

services:
  # --- API GATEWAY ---
  nginx-gateway:
    image: nginx:latest
    container_name: wardrobe-gateway
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react-frontend
      - auth-service
      - inventory-service
    networks:
      - wardrobe-network

  # --- FRONTEND ---
  react-frontend:
    build:
      context: ./apps/react-frontend
    container_name: react-frontend
    volumes:
      - ./apps/react-frontend:/app
      - /app/node_modules
    networks:
      - wardrobe-network

  # --- BACKEND SERVICES ---
  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: auth-service
    environment:
      - PORT=3001
      - RMQ_URL=amqp://rabbitmq:5672
      - MONGO_URI=mongodb://auth-db:27017/wardrobe_auth
    depends_on:
      - rabbitmq
      - auth-db
    networks:
      - wardrobe-network

  inventory-service:
    build:
      context: .
      dockerfile: ./apps/inventory-service/Dockerfile
    container_name: inventory-service
    environment:
      - PORT=3002
      - RMQ_URL=amqp://rabbitmq:5672
      - MONGO_URI=mongodb://inventory-db:27017/wardrobe_inventory
    depends_on:
      - rabbitmq
      - inventory-db
    networks:
      - wardrobe-network

  # --- INFRASTRUCTURE ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: wardrobe-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wardrobe-network

  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27018:27017"
    volumes:
      - ./infrastructure/mongodb/auth_data:/data/db
    networks:
      - wardrobe-network

  inventory-db:
    image: mongo:latest
    container_name: inventory-db
    ports:
      - "27019:27017"
    volumes:
      - ./infrastructure/mongodb/inventory_data:/data/db
    networks:
      - wardrobe-network

networks:
  wardrobe-network:
    driver: bridge