/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type {
  DashboardControllerGetHomeDashboardParams,
  DashboardResponseDto
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getDashboard = () => {
/**
 * Single endpoint for the home page. Aggregates weather, AI outfit recommendation, recent items and wardrobe stats in one call (BFF pattern). Weather is cached for 30 minutes; OOTD falls back to rule-based logic if Gemini is unavailable.
 * @summary Get home dashboard data
 */
const dashboardControllerGetHomeDashboard = (
    params?: DashboardControllerGetHomeDashboardParams,
 options?: SecondParameter<typeof customInstance<DashboardResponseDto>>,) => {
      return customInstance<DashboardResponseDto>(
      {url: `/dashboard/home`, method: 'GET',
        params
    },
      options);
    }
  return {dashboardControllerGetHomeDashboard}};
export type DashboardControllerGetHomeDashboardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDashboard>['dashboardControllerGetHomeDashboard']>>>
