/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type {
  WeatherControllerGetWeatherParams,
  WeatherResponseDto
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getWeather = () => {
/**
 * Fetches current weather data from OpenWeatherMap. Results are cached for 30 minutes per coordinate.
 * @summary Get current weather by coordinates
 */
const weatherControllerGetWeather = (
    params: WeatherControllerGetWeatherParams,
 options?: SecondParameter<typeof customInstance<WeatherResponseDto>>,) => {
      return customInstance<WeatherResponseDto>(
      {url: `/weather`, method: 'GET',
        params
    },
      options);
    }
  return {weatherControllerGetWeather}};
export type WeatherControllerGetWeatherResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWeather>['weatherControllerGetWeather']>>>
