/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  WeatherControllerGetWeatherParams,
  WeatherResponseDto
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Fetches current weather data from OpenWeatherMap. Results are cached for 30 minutes per coordinate.
 * @summary Get current weather by coordinates
 */
export const weatherControllerGetWeather = (
    params: WeatherControllerGetWeatherParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<WeatherResponseDto>(
      {url: `/weather`, method: 'GET',
        params, signal
    },
      options);
    }




export const getWeatherControllerGetWeatherQueryKey = (params?: WeatherControllerGetWeatherParams,) => {
    return [
    `/weather`, ...(params ? [params] : [])
    ] as const;
    }


export const getWeatherControllerGetWeatherQueryOptions = <TData = Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError = void>(params: WeatherControllerGetWeatherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWeatherControllerGetWeatherQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof weatherControllerGetWeather>>> = ({ signal }) => weatherControllerGetWeather(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WeatherControllerGetWeatherQueryResult = NonNullable<Awaited<ReturnType<typeof weatherControllerGetWeather>>>
export type WeatherControllerGetWeatherQueryError = void


export function useWeatherControllerGetWeather<TData = Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError = void>(
 params: WeatherControllerGetWeatherParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof weatherControllerGetWeather>>,
          TError,
          Awaited<ReturnType<typeof weatherControllerGetWeather>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWeatherControllerGetWeather<TData = Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError = void>(
 params: WeatherControllerGetWeatherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof weatherControllerGetWeather>>,
          TError,
          Awaited<ReturnType<typeof weatherControllerGetWeather>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWeatherControllerGetWeather<TData = Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError = void>(
 params: WeatherControllerGetWeatherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current weather by coordinates
 */

export function useWeatherControllerGetWeather<TData = Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError = void>(
 params: WeatherControllerGetWeatherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof weatherControllerGetWeather>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWeatherControllerGetWeatherQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




