/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getApp = () => {
const appControllerGetHello = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/`, method: 'GET'
    },
      options);
    }
  return {appControllerGetHello}};
export type AppControllerGetHelloResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApp>['appControllerGetHello']>>>
