/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type {
  CreateLocationDto,
  UpdateLocationDto
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getLocations = () => {
const locationsControllerCreate = (
    createLocationDto: CreateLocationDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/locations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLocationDto
    },
      options);
    }
  const locationsControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/locations`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Get all locations as a nested tree
 */
const locationsControllerGetLocationsTree = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/locations/tree`, method: 'GET'
    },
      options);
    }
  const locationsControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/locations/${id}`, method: 'GET'
    },
      options);
    }
  const locationsControllerUpdate = (
    id: string,
    updateLocationDto: UpdateLocationDto,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/locations/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateLocationDto
    },
      options);
    }
  const locationsControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/locations/${id}`, method: 'DELETE'
    },
      options);
    }
  return {locationsControllerCreate,locationsControllerFindAll,locationsControllerGetLocationsTree,locationsControllerFindOne,locationsControllerUpdate,locationsControllerRemove}};
export type LocationsControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLocations>['locationsControllerCreate']>>>
export type LocationsControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLocations>['locationsControllerFindAll']>>>
export type LocationsControllerGetLocationsTreeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLocations>['locationsControllerGetLocationsTree']>>>
export type LocationsControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLocations>['locationsControllerFindOne']>>>
export type LocationsControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLocations>['locationsControllerUpdate']>>>
export type LocationsControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLocations>['locationsControllerRemove']>>>
