/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Wardrobe API
 * The Wardrobe App API description
 * OpenAPI spec version: 1.0
 */
import type {
  ItemsControllerCreateBody,
  ItemsControllerUpdateBody
} from '../../model';

import { customInstance } from '../../../services/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getItems = () => {
const itemsControllerCreate = (
    itemsControllerCreateBody: ItemsControllerCreateBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {const formData = new FormData();
if(itemsControllerCreateBody.name !== undefined) {
 formData.append(`name`, itemsControllerCreateBody.name);
 }
if(itemsControllerCreateBody.description !== undefined) {
 formData.append(`description`, itemsControllerCreateBody.description);
 }
if(itemsControllerCreateBody.price !== undefined) {
 formData.append(`price`, itemsControllerCreateBody.price.toString())
 }
if(itemsControllerCreateBody.location !== undefined) {
 formData.append(`location`, itemsControllerCreateBody.location);
 }
if(itemsControllerCreateBody.file !== undefined) {
 formData.append(`file`, itemsControllerCreateBody.file);
 }

      return customInstance<void>(
      {url: `/items`, method: 'POST',
       data: formData
    },
      options);
    }
  const itemsControllerFindAll = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/items`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Get all item attributes/metadata grouped by type
 */
const itemsControllerFindAllAttributes = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/items/attributes`, method: 'GET'
    },
      options);
    }
  const itemsControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/items/${id}`, method: 'GET'
    },
      options);
    }
  const itemsControllerUpdate = (
    id: string,
    itemsControllerUpdateBody: ItemsControllerUpdateBody,
 options?: SecondParameter<typeof customInstance<void>>,) => {const formData = new FormData();
if(itemsControllerUpdateBody.name !== undefined) {
 formData.append(`name`, itemsControllerUpdateBody.name);
 }
if(itemsControllerUpdateBody.description !== undefined) {
 formData.append(`description`, itemsControllerUpdateBody.description);
 }
if(itemsControllerUpdateBody.price !== undefined) {
 formData.append(`price`, itemsControllerUpdateBody.price.toString())
 }
if(itemsControllerUpdateBody.location !== undefined) {
 formData.append(`location`, itemsControllerUpdateBody.location);
 }
if(itemsControllerUpdateBody.file !== undefined) {
 formData.append(`file`, itemsControllerUpdateBody.file);
 }

      return customInstance<void>(
      {url: `/items/${id}`, method: 'PATCH',
       data: formData
    },
      options);
    }
  const itemsControllerRemove = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/items/${id}`, method: 'DELETE'
    },
      options);
    }
  return {itemsControllerCreate,itemsControllerFindAll,itemsControllerFindAllAttributes,itemsControllerFindOne,itemsControllerUpdate,itemsControllerRemove}};
export type ItemsControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getItems>['itemsControllerCreate']>>>
export type ItemsControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getItems>['itemsControllerFindAll']>>>
export type ItemsControllerFindAllAttributesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getItems>['itemsControllerFindAllAttributes']>>>
export type ItemsControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getItems>['itemsControllerFindOne']>>>
export type ItemsControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getItems>['itemsControllerUpdate']>>>
export type ItemsControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getItems>['itemsControllerRemove']>>>
